apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-jwt-deployment
  labels:
    app: spring-jwt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-jwt
  template:
    metadata:
      labels:
        app: spring-jwt
    spec:
      containers:
        - name: spring-jwt
          image: spring-jwt:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-jwt-service
spec:
  type: NodePort
  selector:
    app: spring-jwt
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100